Repository shopware/composer-project, pull requests merged in 2018-08, with the labels that each got.

#14 Sanitize loaded Shopware version from Composer
  app/AppKernel.php
Labels: Scheduled

#16 Readme: Add Configuration section
  README.md
Labels: Incomplete

#18 Handle composer version numbers with leading v
  app/AppKernel.php
Labels: Quick-Pick
